#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
安装仓库 Git 钩子

    python tools/install_hooks.py

当前安装：
    pre-commit —— 提交前调用 tools/check_secrets.py 扫描暂存区，
                  发现疑似敏感信息则中断提交（可用 git commit --no-verify 跳过）。

钩子写在 .git/hooks/ 下，不随仓库分发；换机器后需重新执行本脚本。
"""
from __future__ import annotations

import os
import stat
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_secrets import GIT  # noqa: E402  （复用同一套 git 定位逻辑）

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY = sys.executable.replace("\\", "/")
SCAN = ROOT.replace("\\", "/") + "/tools/check_secrets.py"

# 说明：**不能用 $PWD 拼脚本路径**。Git 的 sh 给出的是 POSIX 风格路径
# （/e/用户/...），交给原生 python.exe 时 MSYS 会做路径转换，而仓库路径一旦
# 含非 ASCII 字符（中文用户名/目录名），转换结果会损坏，报
# "can't open file 'E:\e\...'"。因此这里内置 Windows 形式的绝对路径。
#
# 解释器选择顺序：先试内置的托管 Python（绝对路径，最可靠），再试 PATH 上的
# python3/python/py。**每个都要用 -c 探活**——Windows 的
# %LOCALAPPDATA%\Microsoft\WindowsApps\python.exe 是应用商店占位存根，
# command -v 找得到但一执行就失败且不输出，会把提交静默拦下。
HOOK_TEMPLATE = """#!/bin/sh
# Secret scan before commit (generated by tools/install_hooks.py)
# Bypass once: git commit --no-verify
SCAN="__SCAN__"
BAKED="__PY__"
[ -f "$SCAN" ] || SCAN="$PWD/tools/check_secrets.py"
if [ ! -f "$SCAN" ]; then
  echo "check_secrets: scanner not found, skipping secret scan"
  exit 0
fi
for PY in "$BAKED" python3 python py; do
  [ -n "$PY" ] || continue
  command -v "$PY" >/dev/null 2>&1 || continue
  # 探活：排除应用商店存根等"存在但不可用"的解释器
  "$PY" -c "import sys" >/dev/null 2>&1 || continue
  "$PY" "$SCAN" --staged
  exit $?
done
echo "check_secrets: no usable python interpreter, skipping secret scan"
exit 0
"""


def main() -> int:
    git_dir = subprocess.run(
        [GIT, "rev-parse", "--git-dir"], cwd=ROOT, capture_output=True
    ).stdout.decode().strip() or ".git"
    hooks_dir = os.path.join(ROOT, git_dir, "hooks")
    os.makedirs(hooks_dir, exist_ok=True)

    body = HOOK_TEMPLATE.replace("__PY__", PY).replace("__SCAN__", SCAN)
    path = os.path.join(hooks_dir, "pre-commit")
    # 用 UTF-8：解释器绝对路径可能含非 ASCII 字符（用户名），无法用 ascii 编码
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    os.chmod(path, os.stat(path).st_mode | stat.S_IEXEC)

    print("installed: %s" % os.path.relpath(path, ROOT))
    print("interpreter: %s" % PY)
    return 0


if __name__ == "__main__":
    sys.exit(main())
